apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- policies-payload-configmap.yaml
- policy-script-configmap.yaml
- import-policies-job.yaml

patches:
- target:
    group: batch
    version: v1
    kind: Job
    name: import-policies-job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: central-stackrox.apps.cluster-rbz2x.rbz2x.sandbox1572.opentlc.com
