apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/instance: acs-config-pipeline-app
  name: copy-and-commit
  namespace: stackrox
spec:
  steps:
  - env:
    - name: WORKSPACE_SSH_DIRECTORY_BOUND
      value: $(workspaces.ssh-directory.bound)
    - name: WORKSPACE_SSH_DIRECTORY_PATH
      value: $(workspaces.ssh-directory.path)
    image: registry.redhat.io/ubi9/toolbox
    name: ""
    script: "#!/usr/bin/env bash\nset -eu\n\ncd ${WORKSPACE_SSH_DIRECTORY_PATH}\nfor
      i in $(ls); do\n  cp `readlink $i` ~/.ssh\ndone          \n\nchmod 700 ~/.ssh\nchmod
      400 ~/.ssh/id_ed25519\nchmod 440 ~/.ssh/config\nchmod 600 ~/.ssh/known_hosts\n\ncd
      /workspace/output/acs-demo\neval \"$(ssh-agent -s)\"\nssh-add ~/.ssh/id_ed25519\ngit
      config --global --add safe.directory /workspace/output/acs-demo\ngit config
      --global user.email \"cdr@redhat.com\"\ngit config --global user.name \"Casey
      Robb\"\ncp -v /workspace/output/acs-policies/policies-payload-cm.yaml ./app/policy/policies-payload-cm.yaml\ngit
      add ./app/policy/policies-payload-cm.yaml\ngit commit -m \"Update from policies-pipeline
      $(date +%s)\"\ngit push origin HEAD:master\n"
    workingDir: $(workspaces.output.path)
  workspaces:
  - description: Workspace onto which the file is written.
    name: output
    optional: true
  - description: |
      A .ssh directory with private key, known_hosts, config, etc. Copied to
      the user's home before git commands are executed. Used to authenticate
      with the git remote when performing the clone. Binding a Secret to this
      Workspace is strongly recommended over other volume types.
    name: ssh-directory
    optional: true
