apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-acs-policies
  namespace: stackrox
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: trigger-template-policy-cm-builder
