apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: event-listener-acs-policies
  name: el-event-listener-acs-policies
  namespace: stackrox
spec:
  host: el-event-listener-acs-policies.apps.cluster-jjjw9.jjjw9.sandbox1036.opentlc.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-event-listener-acs-policies
    weight: 100
  wildcardPolicy: None
