apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- copy-and-commit-task.yaml
- write-file-task.yaml
- yq-task.yaml
- policy-cm-builder-pipeline.yaml
- trigger-template.yaml
- eventlistener-route.yaml
- eventlistener.yaml
- policies-trigger.yaml

patches:
- target:
    group: route.openshift.io
    version: v1
    kind: Route
    name: el-event-listener-acs-policies
  patch: |-
    - op: replace
      path: /spec/host
      value: el-event-listener-acs-policies-stackrox.apps.cluster-t7q5j.t7q5j.sandbox2685.opentlc.com
