apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- copy-and-commit-task.yaml
- write-file-task.yaml
- yq-task.yaml
- policy-cm-builder-pipeline.yaml
- trigger-template.yaml
- eventlistener-route.yaml
- eventlistener.yaml
- policies-trigger.yaml
