apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- git-credentials-sealedsecret.yaml
- copy-and-commit-task.yaml
- write-file-task.yaml
- yq-task.yaml
- policy-cm-builder-pipeline.yaml
